name: intern_task
description: "A professional full-stack notes application with Flutter + FastAPI + MySQL"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # HTTP Client
  http: ^1.1.2
  dio: ^5.4.0
  
  # JSON Serialization
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # UI Components
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  
  # Authentication
  flutter_secure_storage: ^9.0.0
  
  # Date Handling
  intl: ^0.19.0
  
  # Networking
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  
  # Testing
  mockito: ^5.4.4
  http_mock_adapter: ^0.6.0

flutter:
  uses-material-design: true
  
  # Assets (currently empty, will be added later)
  # assets:
  #   - assets/images/
  #   - assets/icons/
    
  # Fonts (using system fonts for now)
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700
